"""setup

Revision ID: 58dd370eb710
Revises: 93f29634f1c7
Create Date: 2025-06-17 17:28:30.952330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58dd370eb710'
down_revision = '93f29634f1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hero_powers', 'hero_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('hero_powers', 'power_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hero_powers', 'power_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hero_powers', 'hero_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
